# Generated by Django 4.2.9 on 2024-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingridient',
            name='value',
            field=models.CharField(help_text='Ingridient value', max_length=255),
        ),
    ]
